job:
  date: 2024-04-10
  start_time: 09-03-20
  details:
    model_name: Llama-2-13b-chat-hf
    system_name: argonne-swing
    num_tokens: 32
    batch_size: 32
    hf_name: meta-llama/Llama-2-13b-chat-hf
    prompt-C: What are some effective strategies for managing st
