job:
  date: 2024-04-22
  start_time: 09-27-09
  details:
    model_name: Mixtral-8x7B-v0.1
    system_name: argonne-swing
    num_tokens: 32
    batch_size: 32
    hf_name: mistralai/Mixtral-8x7B-v0.1
    prompt-C: What are some effective strategies for managing st
