job:
  date: 2024-05-13
  start_time: 14-48-50
  details:
    model_name: Llama-2-7b-chat-hf
    system_name: M1-Pro
    num_tokens: 32
    batch_size: 32
    hf_name: meta-llama/Llama-2-7b-chat-hf
    prompt-F: /* An improved random number generation package.
    prompt-G: /*This is a version (aka ptmalloc2) of malloc/free
    prompt-H: /void _quicksort (void *const pbase, size_t total_
    prompt-I: #include <alloca.h>
#include <limits.h>
#include <
