job:
  date: 2024-03-27
  start_time: 15-46-40
  details:
    model_name: Mistral-7B-v0.1
    system_name: M1-Pro
    num_tokens: 64
    batch_size: 32
    hf_name: mistralai/Mistral-7B-v0.1
    prompt-A: What is the capital of France?
