job:
  date: 2024-03-31
  start_time: 16-48-55
  details:
    model_name: falcon-7b
    system_name: palmetto-v100
    num_tokens: 32
    batch_size: 32
    hf_name: tiiuae/falcon-7b
    prompt-I: #include <alloca.h>
#include <limits.h>
#include <
