job:
  date: 2024-04-03
  start_time: 06-26-50
  details:
    model_name: Mistral-7B-v0.1
    system_name: argonne-swing
    num_tokens: 32
    batch_size: 32
    hf_name: mistralai/Mistral-7B-v0.1
    prompt-C: What are some effective strategies for managing st
