job:
  date: 2024-03-28
  start_time: 16-35-44
  details:
    model_name: Llama-2-7b-chat-hf
    system_name: M1-Pro
    num_tokens: 64
    batch_size: 32
    hf_name: meta-llama/Llama-2-7b-chat-hf
    prompt-H: /void _quicksort (void *const pbase, size_t total_
    prompt-I: #include <alloca.h>
#include <limits.h>
#include <
