job:
  date: 2024-04-18
  start_time: 10-13-21
  details:
    model_name: falcon-40b
    system_name: argonne-swing
    num_tokens: 32
    batch_size: 32
    hf_name: tiiuae/falcon-40b
    prompt-C: What are some effective strategies for managing st
