job:
  date: 2024-03-28
  start_time: 09-38-59
  details:
    model_name: Llama-2-7b-chat-hf
    system_name: M1-Pro
    num_tokens: 64
    batch_size: 32
    hf_name: meta-llama/Llama-2-7b-chat-hf
    prompt-A: What is the capital of France?
