job:
  date: 2024-03-29
  start_time: 13-02-36
  details:
    model_name: falcon-7b
    system_name: argonne-swing
    num_tokens: 32
    batch_size: 32
    hf_name: tiiuae/falcon-7b
    prompt-C: What are some effective strategies for managing st
